// src/lib/types/vent.ts
import { ObjectId } from 'mongodb';

export interface ReactionCounts {
  [key: string]: number; // e.g., { relate: 10, support: 5, hug: 12 }
}

export interface Vent {
  _id?: ObjectId; // Optional because it's generated by MongoDB
  userId: string; // Anonymous session ID or NextAuth user ID
  pseudonym?: string; // For anonymous users, can be generated
  avatarSeed?: string; // For generating a unique avatar for anonymous users
  content: string;
  emotionTag: string; // e.g., '🥺 Anxious', '😡 Angry'
  topicCategory: string; // e.g., 'Exams', 'Relationships'
  createdAt: Date;
  reactions: ReactionCounts;
  commentCount: number;
  isAnonymous: boolean; // To distinguish between full auth and anonymous session
}
